import "./globals.css";
import { Spectral } from "next/font/google";

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["400", "700"],
});
export const metadata = {
  title: "Evan Lin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        {/* Preconnect to improve font load performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        {/* Prefer using the Google Fonts CSS already loaded by next/font, but preload an early CSS resource if available */}
      </head>
      <body className={`${spectral.className} bg-gray-100 h-full`}>
        {children}
      </body>
    </html>
  );
}
