import "./globals.css";
import { Spectral } from "next/font/google";

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["400", "700"],
});
export const metadata = {
  title: "Evan Lin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${spectral.className} bg-gray-100 h-full`}>{children}</body>
    </html>
  );
}
